a better ItemBuilder
Minemobs/MinemobsUtils pull request #9
Opened 2022-03-19 19:40 UTC by NoaLeGeek

accept minemobs, accept...

2022-03-23 10:53 UTC, NoaLeGeek commented
bruh l'erreur elle vient pas de moi

2022-03-23 21:55 UTC, Minemobs requested changes
You should use a ternary operator instead

2022-03-24 19:53 UTC, NoaLeGeek commented
lamba go brrr just explain how to modify a pull request

2022-03-24 19:55 UTC, NoaLeGeek commented
* What went wrong:
1 actionable task: 1 executed
Execution failed for task ':compileJava'.
> Could not resolve all files for configuration ':compileClasspath'.
   > Could not download spigot-1.17.1-R0.1-SNAPSHOT.jar (org.spigotmc:spigot:1.17.1-R0.1-SNAPSHOT:20210708.170[25](https://github.com/Minemobs/MinemobsUtils/runs/5613226018?check_suite_focus=true#step:5:25)3-1): Skipped due to earlier error

2022-03-24 19:56 UTC, Minemobs commented
haha don't care

2022-03-24 20:00 UTC, Minemobs approved these changes

2022-03-24 20:05 UTC, Minemobs requested changes

2022-03-24 20:05 UTC, Minemobs commented on src/main/java/fr/minemobs/minemobsutils/utils/ItemBuilder.java
> +        Arrays.stream(flags).forEach(this::addItemFlag);
```
/home/runner/work/MinemobsUtils/MinemobsUtils/src/main/java/fr/minemobs/minemobsutils/utils/ItemBuilder.java:151: error: cannot find symbol
        Arrays.stream(flags).forEach(this::addItemFlag);
        ^
  symbol:   variable Arrays
  location: class ItemBuilder

```

2022-03-25 17:17 UTC, Minemobs approved these changes

2022-03-25 17:18 UTC, merged